version: '3.3'

services:
  app:
    build: .
    container_name: soda_image_segmentation
    restart: always
    ports:
      - "2223:22"  # Add this line to expose SSH
      - "9240:9240"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    volumes:
      - .:/app
    environment:
      - OPENAI_ORG_KEY=${OPENAI_ORG_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PYTHONPATH=/app  # Add this line to set the PYTHONPATH

    command: bash -c "service ssh start && ./start.sh"  # Start SSH service
    
